# Generated by Django 4.1 on 2024-01-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0003_tbl_location_districtid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Category',
            fields=[
                ('Categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('Categoryname', models.CharField(max_length=50)),
                ('Categorydesc', models.CharField(max_length=100)),
                ('Categoryimg', models.ImageField(upload_to='')),
            ],
        ),
    ]
