# Generated by Django 4.1 on 2024-02-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller', '0005_alter_tbl_product_productdesc'),
        ('Guest', '0005_alter_tbl_customer_loginid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_cart',
            fields=[
                ('Cartid', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.BigIntegerField()),
                ('Cartdate', models.DateField()),
                ('Status', models.CharField(max_length=30)),
                ('Productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_product')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.login')),
            ],
        ),
    ]
