# Generated by Django 4.1 on 2024-02-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='Cartdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
