# Generated by Django 4.1 on 2024-02-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_tbl_cart_cartdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='Quantity',
            field=models.BigIntegerField(default=''),
        ),
    ]
