# Generated by Django 4.1 on 2024-01-27 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0005_alter_tbl_customer_loginid_and_more'),
        ('ADMIN', '0005_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Product',
            fields=[
                ('Productid', models.AutoField(primary_key=True, serialize=False)),
                ('Productname', models.CharField(max_length=50)),
                ('Productdesc', models.CharField(max_length=100)),
                ('Productprice', models.BigIntegerField()),
                ('productimage1', models.ImageField(upload_to='')),
                ('Subcategoryimg', models.ImageField(upload_to='')),
                ('Productregdate', models.DateField(auto_now_add=True)),
                ('Sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_seller')),
                ('Subcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADMIN.tbl_subcategory')),
            ],
        ),
    ]
