# Generated by Django 4.1 on 2024-01-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_tbl_product_productstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_product',
            old_name='Subcategoryimg',
            new_name='productimage2',
        ),
    ]
