# Generated by Django 4.1 on 2024-01-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_alter_tbl_customer_loginid_and_more'),
        ('Seller', '0003_rename_subcategoryimg_tbl_product_productimage2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='Sellerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.login'),
        ),
    ]
