# Generated by Django 4.1 on 2024-01-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_alter_tbl_product_sellerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='Productdesc',
            field=models.CharField(max_length=1000),
        ),
    ]
