# Generated by Django 4.1 on 2024-01-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('Loginid', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=15)),
                ('Status', models.CharField(max_length=15)),
            ],
        ),
    ]
