# Generated by Django 4.1 on 2024-01-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0004_tbl_category'),
        ('Guest', '0002_tbl_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_customer',
            name='locationid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ADMIN.tbl_location'),
        ),
    ]
