# Generated by Django 4.1 on 2024-01-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0005_tbl_subcategory'),
        ('Guest', '0004_tbl_customer_regdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_customer',
            name='Loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.login'),
        ),
        migrations.AlterField(
            model_name='tbl_customer',
            name='locationid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADMIN.tbl_location'),
        ),
        migrations.CreateModel(
            name='Tbl_Seller',
            fields=[
                ('Sellerid', models.AutoField(primary_key=True, serialize=False)),
                ('Sellername', models.CharField(max_length=25)),
                ('Selleremail', models.CharField(max_length=30)),
                ('SellerGender', models.CharField(max_length=20)),
                ('SellerPhone', models.BigIntegerField()),
                ('Regdate', models.DateField(auto_now_add=True)),
                ('Housename', models.CharField(max_length=30)),
                ('pincode', models.BigIntegerField()),
                ('Sellerimage', models.ImageField(upload_to='')),
                ('Idproof', models.ImageField(upload_to='')),
                ('Loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.login')),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADMIN.tbl_location')),
            ],
        ),
    ]
